### ISSUE TITLE
Question about the finetuning settings？

### ISSUE THREAD

**Issue by Elliot-QxZhang** [TencentAILabHealthcare/ConCL#2]
Hi, thanks for sharing this work. I wonder during the finetuning stage, do you use any annotations from Glas/CRAG dataset, or just finetune the detection head in SSL manner?

**Comment by Jiawei-Yang** [comment]
Hi, we follow the standard setting in other SSL works: use the pre-trained weights as initialization and fine-tune the model end-to-end (so both backbone and detection heads are trained) using supervision.

Yes, we use all annotations from Glas/CRAG dataset for fine-tuning unless otherwise notified. We did not freeze the backbone.

**Comment by Elliot-QxZhang** [comment]
I understand! Thank you for your reply!
